#!/bin/sh
TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
LOG_FOLDER=/tmp/mesher-monitor
HOSTNAME=`hostname`

mkdir -p $LOG_FOLDER
nohup mesher-experimental $3 > $LOG_FOLDER/mesher-$HOSTNAME.log 2>&1 &
sleep 1