#!/bin/sh

TIMEOUT_S="10"
LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"

while [ true ]; do
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if test timed out / the experiment is finished
    if [ "$LATER" -lt `date +%s` ]; then
       echo "Finished: Experiment time over on $HOSTNAME; killing mesher-experimental"
       killall mesher-experimental
       exit 0
    fi

    sleep 15
done
